#import "./fragments.gql"

# Write your query or mutation here
mutation CreateUser($firstName: String!, $lastName: String!, $email: String!, $password: String!) {
  createUser(signupInput: { firstName: $firstName, lastName: $lastName, email: $email, password: $password }) {
    ...UserInfo
  }
}

mutation CreatePost($postCreationInput: PostCreationInput!) {
  createPost(postCreationInput: $postCreationInput) {
    ...PostInfo
  }
}

mutation EditUser($firstName: String!, $lastName: String!, $id: String!) {
  editUser(userEditInput: { firstName: $firstName, lastName: $lastName, id: $id }) {
    ...UserInfo
  }
}
