#import "./fragments.gql"

query GetUsers {
  users {
    ...UserInfo
  }
}

query GetPost($id: String!) {
  post(where: { id: $id }) {
    ...PostDetail
  }
}

query GetPosts {
  posts {
    ...PostListItem
  }
}

query GetPostsByAuthor($id: StringFilter!) {
  posts(where: { author: { id: $id } }) {
    ...PostListItem
  }
}
